name       : haskell-doclayout
version    : 0.3
release    : 1
source     :
    - https://hackage.haskell.org/package/doclayout-0.3/doclayout-0.3.tar.gz : 87aad514e631f2ccc4a496f3fa74a2beda5f9ad53b660d1033cd338904e6b6f2
license    : BSD-3-Clause
component  : programming.haskell
summary    : A prettyprinting library for laying out text documents.
description: |
    doclayout is a prettyprinting library for laying out text documents, with several features not present in prettyprinting libraries designed for code. It was designed for use in pandoc.
builddeps  :
    - haskell-cabal-install
    - haskell-safe-devel
rundeps    :
    - devel:
        - haskell-safe-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
